// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef starter_h
#define starter_h
#include <Fl/Fl_Box.H>
#include <Fl/Fl_Window.H>
#include <Fl/Fl_Button.H>
#include <cstdlib>
#include <string.h>
#include <iostream>
#endif
