// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef flPhase6_h
#define flPhase6_h


#include <FL/Fl_Select_Browser.h>
#include <FL/Fl_Button.h>
#include <FL/Fl_Check_Button.h>
#include <FL/Fl_File_Chooser.h>
#include <FL/Fl_Native_File_Chooser.H>
#include <FL/Fl_Input.h>
#include <FL/Fl_Box.h>
#include <FL/Fl_Menu_Item.h>
#include <FL/Fl_Menu_Bar.h>
#include <FL/Fl_Progress.h>
#include <FL/Fl_Return_Button.h>
#include <FL/Fl_Value_Output.h>
#include <FL/Fl_Value_Slider.h>
#include <FL/Fl_Window.h>

#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_JPEG_Image.H>
#include <FL/Fl_XPM_Image.H>
#include <FL/Fl_GIF_Image.H>
#include <FL/Fl_Image.H>
#include <FL/Fl_Shared_Image.H>
#include <FL/fl_draw.H>


extern Fl_Check_Button* umkehrstellen;
extern Fl_Input* antwort;
extern Fl_Input* antwort_angeben;
extern Fl_Input* frage_angeben;
extern Fl_Box* meldungen;
extern Fl_Box* frage;
extern Fl_Button* pic_b;
extern Fl_Progress* fortschritt;
extern Fl_Value_Output* fehler;
extern Fl_Value_Output* richtig;
extern Fl_Window* win;
extern Fl_Window* win_start;
extern Fl_Window* win_add;
extern Fl_Window* win_edit;
extern Fl_Window* win_liste;


extern void cb_abbrechen(Fl_Button*, void*);
extern void cb_abgeben(Fl_Return_Button*, void*);
extern void cb_add(Fl_Menu_Item*, void*);
extern void cb_add_now(Fl_Return_Button*, void*);
extern void cb_add_pic(Fl_Menu_Item*, void*);
extern void cb_add_pic_now(Fl_Menu_Item*, void*);
extern void cb_browser(Fl_Select_Browser* b, void*);
extern void cb_edit(Fl_Menu_Item*, void*);
extern void cb_searchedit(Fl_Menu_Item*, void*);
extern void cb_edit_now(Fl_Return_Button*, void*);
extern void cb_exit(Fl_Menu_Item*, void*);
extern void cb_liste(Fl_Menu_Item*, void*);
extern void cb_new(Fl_Menu_Item*, void*);
extern void cb_open(Fl_Menu_Item*, void*);
extern void cb_open_pic(Fl_Button*, void*);
extern void cb_pic_rect(Fl_Button*, void*);
extern void cb_remove(Fl_Menu_Item*, void*);
extern void cb_save(Fl_Menu_Item*, void*);
extern void cb_save_as(Fl_Menu_Item*, void*);
extern void cb_start(Fl_Menu_Item*, void*);
extern void cb_start_now(Fl_Return_Button*, Fl_Value_Slider*);
extern void cb_suche(Fl_Menu_Item*, void*);
extern void cb_suche_now(Fl_Input* o, void*);
extern void cb_test_abbrechen(Fl_Button*, void*);
#endif
