// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef fldesktop_h
#define fldesktop_h
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_File_Chooser.H>
#include <cstdlib>
#include <string.h>
#include <iostream>
#endif
