// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef flPear_h
#define flPear_h
#include <string.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input* hddimg;
extern Fl_Input* cdimg;
extern Fl_Input *boot_args;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button* fscreen;
extern Fl_Check_Button* g4use;
extern Fl_Check_Button* ramuse;
extern Fl_Check_Button* netuse1;
extern Fl_Check_Button* netuse2;
#include <FL/Fl_Button.H>
extern void hdd_callback(Fl_Button*, void*);
extern void cd_callback(Fl_Button*, void*);
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice* res;
extern Fl_Check_Button* cd_dev_check;
extern void cd_dev_callback(Fl_Check_Button*, void*);
#include <FL/Fl_Dial.H>
extern void dial_change(Fl_Dial*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output* valuemoutput;
#include <FL/Fl_Return_Button.H>
extern void run_callback(Fl_Return_Button*, void*);
#include <FL/Fl_File_Chooser.H>
extern void save_callback(Fl_Button*, void*);
extern void locate_callback(Fl_Button*, void*);
#endif
